In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype = 'int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 6.0], [6.0, 7.0, 3.0]])
print(b)

[[9. 8. 6.]
 [6. 7. 3.]]


In [4]:
# Get dimension

a.ndim

1

In [5]:
# Get Shape

b.shape

(2, 3)

# Accessing/Changing specific elements, rows, columns etc


In [6]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
# Get Shape 
print(a.shape)

# Get a specific element [r, c]
a[1, 5] # ['row index', 'column index']


(2, 7)


13

In [8]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [9]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [10]:
# Get a range of numbers, skipping two indexes
# [startindex:endindex:skipsize]

a[0, 1:6:2]

array([2, 4, 6])

In [11]:
# Replacing a value at a specific index

a[1, 5] = 20
print(a)

# Replacing the value of an entire column with a single value
a[:, 2] = 5

# Replacing the value of an entire column with diff values
a[:, 2] = [1, 2]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [12]:
# 3D EXAMPLE-
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
print(b)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# Get a specific element (e.g the value 4 in the first matrix)

b[0,1,1]  # ['index of matrix', 'index of row', 'index of column']

# Get the first row from the first array and the 2nd row from the 2nd array
b[:, 1, :] #[': - removes the first row of both arrays', '1 - selects the values of the 2nd row in both arrays', ': - gets the values of the rows']

# Play with the values of the indexes to get a hand of it 

array([[3, 4],
       [7, 8]])

In [14]:
# Changes the values of rows in a 3D Array

b[:, 1, :] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# INITIALIZING DIFF TYPES OF ARRAYS

In [15]:
# All 0s Matrix

# np.zeros(5)

# np.zeros((2, 3))

# np.zeros((2, 3, 3))

np.zeros((2, 3, 3, 2), dtype='int32')

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]]])

In [16]:
# All 1s Matrix
np.ones((4,2,4), dtype = 'int32')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [17]:
# Any other number

np.full((2,2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [18]:
# Any other number (full_like)
np.full_like(a, 4) # Creates a new array with the shape of an existing array 

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [19]:
# Random decimal numbers 

np.random.rand(4, 2)

# Array filled with random decimals from the shape of an existing array 
np.random.random_sample(a.shape)

array([[0.92270261, 0.0442685 , 0.30449029, 0.54817659, 0.02652848,
        0.90764577, 0.87974199],
       [0.25610706, 0.86885336, 0.86365634, 0.64504734, 0.39746316,
        0.0629733 , 0.84382059]])

In [20]:
# ARRAY WITH RANDOM INTEGER VALUES

# np.random.randint(7, size=(3, 4))

np.random.randint(-7, 11, size=(3, 4)) # Random integers from -7 to 11

array([[-4,  2,  1,  7],
       [-5,  8,  6, -3],
       [-2, -5, -5, -5]])

In [21]:
# The Identity Matrix - is a square matrix with 1 as it's diagonal value

np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [22]:
# Repeating an array 

arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [23]:
# EXERCISE

output = np.ones((5, 5))
print(output)

zeros = np.zeros((3,3))

zeros[1,1] = 9
print(zeros)

output[1:4, 1:4] = zeros
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# BE CAREFUL WHEN COPYING ARRAYS

In [24]:
# The proper way to copy an array 

a = np.array([1,2,3])
b = a.copy
# b[1] = 100 # This will give an error, because it's now a copied array
print(a)
# print(b)

[1 2 3]


# MATHEMATICS

In [25]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [26]:
a + 2

array([3, 4, 5, 6])

In [27]:
a - 2

array([-1,  0,  1,  2])

In [28]:
b = np.array([1,0,9,8])
b + a

array([ 2,  2, 12, 12])

In [29]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [30]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# LINEAR ALGEBRA

# NB - The size of the column should be equal to the size of the rows and vice versa

In [31]:
a = np.ones((3,2))
print(a)

b = np.full((2, 3), 2)
print(b)

np.matmul(a, b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2 2]
 [2 2 2]]


array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [32]:
# Find the determinant
c = np.identity(3)

np.linalg.det(c) # Finds the determinant of the linear algebra

1.0

# STATISTICS

In [33]:
stats = np.array([[1,2,3], [4,5,1]])
stats

array([[1, 2, 3],
       [4, 5, 1]])

In [34]:
# stats.min() returns the lowest number in the array
stats.min(axis=1) # axis = 1 returns the lowest number from both rows, axis = 0 returns the first row

array([1, 1])

In [35]:
# stats.max() returns the highest number in the array
stats.max(axis=1) # axis = 1 returns the highest number from both rows, axis = 0 returns the last row

array([3, 5])

In [36]:
# np.sum(stats)

np.sum(stats, axis=0)

array([5, 7, 4])

# REORGANIZING ARRAYS

In [37]:
before = np.array([[1,2,3,4,], [5,6,7,8]])
print(before)

# Reshape to (8, 1)
after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


# VERTICALLY STACKING VECTORS

In [38]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
# HORIZONTAL STACKING 

h1 = np.ones((2, 4))
h2 = np.zeros((2, 7))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.]])

# MISCELLANEOUS

In [40]:
# Load data from file 

file_data = np.genfromtxt('data.txt', delimiter = ',')
file_data = file_data.astype('int32')
file_data

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9,  6,  3,  4,  5,  6],
       [ 3,  5,  6,  4,  6,  7,  8,  9,  6,  3,  4,  5,  6,  7],
       [ 3,  4,  6,  7,  2,  4,  6,  8,  9,  0,  5, 33,  3, 33]])

# Boolean Masking and Advanced Indexing

In [41]:
file_data > 5

array([[False, False, False, False, False,  True,  True,  True,  True,
         True, False, False, False,  True],
       [False, False,  True, False,  True,  True,  True,  True,  True,
        False, False, False,  True,  True],
       [False, False,  True,  True, False, False,  True,  True,  True,
        False, False,  True, False,  True]])

In [42]:
file_data[file_data > 7]

array([ 8,  9,  8,  9,  8,  9, 33, 33])

In [43]:
# You can index with a list in Numpy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [44]:
np.any(file_data > 7, axis = 0)

array([False, False, False, False, False, False,  True,  True,  True,
       False, False,  True, False,  True])

In [45]:
np.any(file_data > 7, axis = 1)

array([ True,  True,  True])

In [46]:
((file_data > 5) & (file_data < 35))

array([[False, False, False, False, False,  True,  True,  True,  True,
         True, False, False, False,  True],
       [False, False,  True, False,  True,  True,  True,  True,  True,
        False, False, False,  True,  True],
       [False, False,  True,  True, False, False,  True,  True,  True,
        False, False,  True, False,  True]])

In [47]:
(~((file_data > 5) & (file_data < 35))) # ~ represents the NOT condition

array([[ True,  True,  True,  True,  True, False, False, False, False,
        False,  True,  True,  True, False],
       [ True,  True, False,  True, False, False, False, False, False,
         True,  True,  True, False, False],
       [ True,  True, False, False,  True,  True, False, False, False,
         True,  True, False,  True, False]])